# Generated by Django 2.0 on 2018-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(default='I:/media/user_dp/anonymous.png', upload_to='user_dp', verbose_name='Profile Picture'),
        ),
    ]
