# Generated by Django 2.0 on 2018-01-27 10:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20180127_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(default='/user_dp/anonymous.png', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='user_dp', verbose_name='Profile Picture'),
        ),
    ]
