# Generated by Django 2.0 on 2018-01-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20180127_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(default='I:\\Projects\\Python\\Django\\myWeb\\mediauser_dp/anonymous.png', upload_to='user_dp', verbose_name='Profile Picture'),
        ),
    ]
