# Generated by Django 2.0 on 2018-01-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rhythmica', '0003_auto_20180124_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
