# Generated by Django 2.0 on 2018-01-26 21:05

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Rhythmica', '0004_auto_20180126_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250, verbose_name='Album Artist')),
                ('albumTitle', models.CharField(max_length=1000, verbose_name='Album Title')),
                ('numOfSongs', models.IntegerField(default=0, verbose_name='Number of Songs')),
                ('genre', models.CharField(blank=True, default='Unknown', max_length=50, verbose_name='Album Genre')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
                ('albumLogo', models.FileField(default='settings.MEDIA_ROOT/song_logos/anonymous.jpg', storage=django.core.files.storage.FileSystemStorage(location='I:/media/'), upload_to='album_logos', verbose_name='Album Logo')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumSongMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('song_title', models.CharField(blank=True, max_length=100, verbose_name='Rename This Song To')),
                ('title_change', models.BooleanField(default=False, verbose_name='Change Song Title')),
                ('is_fav', models.BooleanField(default=False, verbose_name='Favorite')),
                ('logo_change', models.BooleanField(default=False, verbose_name='Song Logo Changed')),
                ('song_logo', models.FileField(upload_to='', verbose_name='New Logo')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rhythmica.Album', verbose_name='Album')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songTitle', models.CharField(max_length=500, verbose_name='Song Title')),
                ('songFormat', models.CharField(max_length=10, verbose_name='Format')),
                ('songDuration', models.TimeField(blank=True, verbose_name='Duration')),
                ('songUrl', models.FileField(upload_to='', verbose_name='Choose Song')),
                ('songLogo', models.FileField(default='settings.MEDIA_ROOT/song_logos/anonymous.jpg', storage=django.core.files.storage.FileSystemStorage(location='I:/media/'), upload_to='song_logos', verbose_name='Choose Logo')),
            ],
        ),
        migrations.AddField(
            model_name='albumsongmap',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rhythmica.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(through='Rhythmica.AlbumSongMap', to='Rhythmica.Song', verbose_name='Songs'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.UserProfile'),
        ),
    ]
