# Generated by Django 2.0 on 2018-01-27 10:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhythmica', '0006_auto_20180127_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumLogo',
            field=models.ImageField(default='/song_logos/anonymous.jpg', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='album_logos', verbose_name='Album Logo'),
        ),
        migrations.AlterField(
            model_name='song',
            name='songLogo',
            field=models.ImageField(default='/song_logos/anonymous.jpg', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='song_logos', verbose_name='Choose Logo'),
        ),
    ]
