# Generated by Django 2.0 on 2018-01-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhythmica', '0009_auto_20180127_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='numOfSongs',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of Songs'),
        ),
    ]
