# Generated by Django 2.0 on 2018-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhythmica', '0010_auto_20180127_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumLogo',
            field=models.ImageField(default='I:\\Projects\\Python\\Django\\myWeb\\mediasong_logos/anonymous.jpg', upload_to='album_logos', verbose_name='Album Logo'),
        ),
    ]
