# Generated by Django 2.0 on 2018-01-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20180127_1626'),
        ('Rhythmica', '0011_auto_20180127_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songLogo',
            field=models.ImageField(default='I:\\Projects\\Python\\Django\\myWeb\\mediasong_logos/anonymous.jpg', upload_to='song_logos', verbose_name='Choose Logo'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('albumTitle', 'user')},
        ),
    ]
