# Generated by Django 2.0 on 2018-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhythmica', '0012_auto_20180128_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumLogo',
            field=models.ImageField(blank=True, default='I:\\Projects\\Python\\Django\\myWeb\\mediasong_logos/anonymous.jpg', upload_to='album_logos', verbose_name='Album Logo'),
        ),
    ]
