# Generated by Django 2.0 on 2018-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhythmica', '0013_auto_20180128_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songLogo',
            field=models.ImageField(default='/song_logos/anonymous.jpg', upload_to='song_logos', verbose_name='Choose Logo'),
        ),
    ]
