# Generated by Django 2.0 on 2018-02-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhythmica', '0017_auto_20180128_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songDuration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duration'),
        ),
    ]
