# Generated by Django 2.0 on 2018-02-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhythmica', '0018_auto_20180205_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsongmap',
            name='song_logo',
            field=models.ImageField(null=True, upload_to='', verbose_name='New Logo'),
        ),
        migrations.AlterField(
            model_name='albumsongmap',
            name='song_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Rename This Song To'),
        ),
    ]
