# Generated by Django 2.0 on 2018-02-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhythmica', '0019_auto_20180206_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songLogo',
            field=models.ImageField(default='/song_logos/anonymous.jpg', null=True, upload_to='song_logos', verbose_name='Choose Logo'),
        ),
    ]
